server:
  port: 9007
spring:
  application:
    name: tensquare-spit #指定服务名
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.194:9300
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true