server:
  port: 9001  # 端口号
spring:
  application:
    name: tensquare-base # 不写也行，但是有个了spring-cloud的就必须要有这个名称
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tensquare_base?characterEncoding=utf8
      username: root
      password: root
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true

  devtools:
    livereload:
      enabled: true #是否支持livereload
      port: 35729
    restart:
      enabled: true #是否支持热部署

